## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
def build(bld):
	obj = bld.create_ns3_module('cgame', ['network', 'wifi'])
	obj.source = [    	
    	'model/cgame-inout-greedy.cc',   
    	'model/cgame-inout-ILPD.cc', 	
          'model/cgame-inout-greedyOrigin.cc', 
           'model/cgame-inout-greedyImproved.cc', 
            'model/cgame-inout-greedyMerged.cc',
            'model/cgame-inout-greedyMergedAnotherGreedy.cc',
    	'model/cgame-class.cc' 
    	 ]
	headers = bld(features='ns3header')  
	headers.module = 'cgame'
	headers.source = [
         'model/cgame-inout-greedy.h',
         'model/cgame-inout-ILPD.h',        
          'model/cgame-inout-greedyOrigin.h',
           'model/cgame-inout-greedyImproved.h',
            'model/cgame-inout-greedyMerged.h',
            'model/cgame-inout-greedyMergedAnotherGreedy.h',
 		 'model/cgame-class.h'
 		
	] 	 	
	bld.ns3_python_bindings()